### ISSUE TITLE
Unambiguous Advertising.

### ISSUE THREAD

**Issue by ftrotter** [thephpleague/uri#110]
## Issue summary

This package does not do what it advertises, and apparently has no intention of doing so. 

### System informations

For the 4.0 (php5) version of the system. The main page examples fail to work.
There is no Uri\create or Uri\merge_query functions. There may be ways to get "equivalent" code to work, but it is not trivial to figure out how, given the documentation, which makes no mention that I can find of "merge_query" for instance.

For the 5.0 (php7) version of the system, the composer based installation that is advertised in the main page fails because an alpha package is required as part of installation (this already has its own ticket).

There is a bug labeled "wont fix" that involves uris that function in common browsers. The reason for not supporting this is that those urls are not RFC3986/RFC3987 compliant. However, they are commonly used in the real world. 

The main page advertises "Modern API to process URI in PHP." But what you mean is "Modern API to process RFC3986/RFC3987 compliant URI in PHP, you will have to write your own layer to handle real-world URI". Your main page advertises "RFC3986 compliant" as a "feature" but it should say "RFC3986 exclusive" as a "project scope limitation".

### Expected result

All of the code listed on this page: https://uri.thephpleague.com/
should work as written. Including the installation instructions. 

Everyone who reads the basic "goal" of your project is going to get the wrong idea about what your relationship to the  RFC3986/RFC3987 standards are. Be upfront about this very substantial limitation. I would have looked elsewhere immediately about this information. 

### Actual result

Spent hours trying to get your code to work merely as advertised, logged to github to find two bugs which are both indications that your project feels no obligation to work as advertised. 

I applaud the fact that you are releasing code. And I am willing to work with code that is rough around the edges, and would even be willing to contribute to projects that are in that state. But you clearly have a beta project here that you are advertising as stable and reliable. Please do not waste my time or others by pretending to be what you are not.

-FT

**Comment by nyamsprod** [comment]
@ftrotter I understand your frustration but I will not tolerate your remarks

> Please do not waste my time or others by pretending to be what you are not.

This is an open source project which by definition contains flaws and can be improved and I acknowledge this fact. Instead of complaining did you offer any help or support to improve the current codebase ? No

Currently **you are the one wasting the maintainer time** by insinuating things which are not facts. A better use of your time would have been:

- creating issue for missing feature or fixing bugs.
- creating PR for missing feature or fixing bugs.
- engaging on a more constructive discussion with the maintainer if the two above can not be done because everyone has something better to do.

If you had done any of the following or just correctly read the documentation, you would have known that:

- The origin of this library is because PHP's internal functions do not respect RFC3986.
- Version 4.0 is EOL
-  Works in underway to replace the package responsible for the composer error shipped by version 4.0 and 5.0.
-  Any decision contains in the issue tracker can always be revisited **without being a jerk**.

Last but not least, this is a Open Source Project with a MIT License this means that your are free to use it **or not**.

**Comment by frankdejonge** [comment]
@ftrotter

> This package does not do what it advertises, and apparently has no intention of doing so.

What do you expect people to do when they read this? Do you expect people to spend their free time and help you out with your issue? You LITERALLY don't have to use this package, nobody forces you to "waste your time". You pretend to speak on behalf of an entire group of people, you don't. If all you add to open-source are comments like these, you only reduce the value of communities.

Since this is just a rude comment I'm going to close this issue.
