### ISSUE TITLE
Doc fixes

### ISSUE THREAD

**Issue by ilyachase** [thephpleague/uri#124]
Docs (http://uri.thephpleague.com/query-parser/1.0/api/) suggests to use `League\Uri\query_parse()`.
But there's no such function. There's `\League\Uri\parse_query()` function (don't know since when).
Also in the docs it says "version 1.0", but release version is 5.3.0 now.

**Comment by nyamsprod** [comment]
the doc is correct 😄 

- [uri-query-parser](http://uri.thephpleague.com/query-parser/) is a new package which is not yet released 
- parse_query is part of the [uri-components](http://uri.thephpleague.com/components/). This package has the following version number as of this writing 1.8.2

the **new** `query_parse` is design to replace **parse_query** which has a design flow that would need BC breakage to fix it.

last but not least `5.3.0` is the current version of the meta-package [uri](http://uri.thephpleague.com/uri/). This package is a empty container exposing only a `composer.json` file since version 5.0 and will be phase out when I have time.

Hope this clarify everything
