### ISSUE TITLE
Url-escaped slash prefixed to normalised path

### ISSUE THREAD

**Issue by inanimatt** [thephpleague/uri#38]
Bit of an odd one:

```php
<?php
require __DIR__.'/vendor/autoload.php';

use League\Uri\Modifiers\Normalize;
use League\Uri\Schemes\Http as HttpUri;

$rawUrl = 'HtTp://vonNN.com/ipsam-nulla-adipisci-laboriosam-dignissimos-accusamus-eum-voluptatem';
$uriNormalizer = new Normalize();
$uri = (string) $uriNormalizer(HttpUri::createFromString($rawUrl));

assert($uri === 'http://vonnn.com/ipsam-nulla-adipisci-laboriosam-dignissimos-accusamus-eum-voluptatem');
echo $uri . PHP_EOL;
```

Currently outputs:

```
Warning: assert(): assert($uri === 'http://vonnn.com/ipsam-nulla-adipisci-laboriosam-dignissimos-accusamus-eum-voluptatem') failed in /var/www/app/erk.php on line 11
http://vonnn.com/%2Fipsam-nulla-adipisci-laboriosam-dignissimos-accusamus-eum-voluptatem
```

An extra `%2F` has snuck in right after the host and initial slash.

**Comment by inanimatt** [comment]
(Sorry, I'd write a proper test-case and dig into the code and offer a PR but I'm really busy :crying_cat_face:)

**Comment by nyamsprod** [comment]
I have found the culprit :+1: 

https://github.com/thephpleague/uri/blob/master/src/Types/ImmutableComponentTrait.php#L109

the bug appears because depending on context the `static::$characters_set` compile the wrong value. This method was added in 4.1 [to improve code speed](https://github.com/thephpleague/uri/pull/28). Seems I'll have to look into it more closely or revert to the previous behavior.

**Comment by nyamsprod** [comment]
The bug fix is now merge on the master branch. I'll close this issue when the new release will be tagged

**Comment by inanimatt** [comment]
Fantastic, thank you!

**Comment by nyamsprod** [comment]
version 4.1.1 is released with the bug fix
