### ISSUE TITLE
Counting non-countable instance.

### ISSUE THREAD

**Issue by Fleshgrinder** [thephpleague/uri#4]
The path interface does not extend the countable interface.

```php
return $this->withProperty('path', $this->path->replace(count($this->path) - 1, $basename.$extension));
```
https://github.com/thephpleague/uri/blob/master/src/Schemes/Ftp.php#L83

**Comment by nyamsprod** [comment]
@Fleshgrinder I don't understand the issue. Please add more description. What does the countable interface has to do with the path ? The path is treated as a string not as an array...

**Comment by Fleshgrinder** [comment]
Sorry, that was completely my fault because I copied the wrong line of code and referenced the wrong file as well. The `count($this->path)` is the problem, your `$this->path` is an instance of `League\Uri\Interfaces\Components\Path` which does not implement any interface that would make it countable at all.

**Comment by nyamsprod** [comment]
OK I see where this question come from, but the answer is straight forward, at least for me:

- The FTP class [extends the HierarchicalUri interface](https://github.com/thephpleague/uri/blob/master/src/Interfaces/Schemes/Ftp.php#L27) 
- the  `HierarchicalUri` interface extends the `Uri` interface
- the `HierarchicalUri` interface differs from the `Uri` interface because [it requires the use of the `HierarchicalPath` interface](https://github.com/thephpleague/uri/blob/master/src/Interfaces/Schemes/HierarchicalUri.php#32)   
- the `HierarchicalPath` interface extends the `Path` interface by implementing a [Collection interface](https://github.com/thephpleague/uri/blob/master/src/Interfaces/Components/HierarchicalPath.php#L25)

So yes the path in any `HierarchicalUri` implemented object is countable.

Why is it like this, well apart from the scheme,  the path component is what make a URI specific. The way the path is structured and parse is scheme dependent. So the basic `Path` interface is not enough to represent a scheme specific path. That is why there also a interface for the `DataPath`.

Of course I'm open to suggestion to improve the architecture, or the documentation around this, if you have a better solution :+1:

**Comment by Fleshgrinder** [comment]
I added some tests yesterday for more specific invalid characters and I ran into the #6 problem again (although the title might be a bit misleading) but it refers to, as does this issue, a complicated structure of your code. I have to review your code further to come up with ideas on resolving it, but I guess it will require a lot of changes and might need to wait for the 5th version.

**Comment by nyamsprod** [comment]
@Fleshgrinder Could you share the added tests so I can validate some changes I've done in my part to simplify the code

**Comment by nyamsprod** [comment]
@Fleshgrinder I think the real issue is the `Uri::resolve` method... I will try to re-implement it differently

**Comment by nyamsprod** [comment]
@Fleshgrinder I've made many changes. to sum up

- All concrete calls have been removed;
- the resolve method has been restricted to the `Http` class;

Hope these changes will resolve your issues

**Comment by Fleshgrinder** [comment]
I pushed it here: https://github.com/Fleshgrinder/uri/blob/improve_host_validation/test/Components/HostTest.php#L60-L139

The tests are from a repository of mine where you might find more interesting tests to copy to your project: https://github.com/Fleshgrinder/php-url-validator/blob/master/test/Fleshgrinder/Validator/URLTest.php

I have some ideas for your library that I will share with you soon. I just do not have enough time right now. :worried:

**Comment by Fleshgrinder** [comment]
Your changes resolve this issue. :+1:
