### ISSUE TITLE
Setting a scheme

### ISSUE THREAD

**Issue by hotrush** [thephpleague/uri#56]
```
$website = League\Uri\Schemes\Http::createFromString('example.com/asd');
$website = $website->withScheme('http');
```

throws an exception

```
RuntimeException [ 0 ]: The URI properties will produce an invalid `League\Uri\Schemes\Http` ~ DOCROOT/vendor/league/uri/src/Schemes/Generic/AbstractUri.php [ 538 ]
```

Is this a normal behavior?

**Comment by nyamsprod** [comment]
yes it is, quick explanation.

From an Uri point of view `example.com/asd` is a **path** NOT a host **and** a path. So your `$website` represents an HTTP URI containing only a path. HTTP Uris can not contain a scheme without an authority. Since `$website` is only a path and you are trying to add a scheme you get a exception as expected.

**Comment by hotrush** [comment]
Ok, thanks. Can close
3 мая 2016 г. 10:06 PM пользователь "ignace nyamagana butera" <
notifications@github.com> написал:
